# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    # Default linters
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Reports suspicious constructs
    - ineffassign   # Detect unused assignments
    - staticcheck   # Comprehensive static analysis
    - unused        # Find unused code

    # Security
    - gosec         # Security problems

    # Bugs
    - bodyclose     # HTTP response body not closed
    - sqlclosecheck # SQL rows/statements not closed
    - nilerr        # Returning nil after checking err != nil
    - noctx         # HTTP requests without context

    # Style
    - gofmt         # Check formatting
    - goimports     # Check imports

    # Performance
    - prealloc      # Slice preallocation suggestions

linters-settings:
  gosec:
    excludes:
      - G104  # Unhandled errors (covered by errcheck)
    config:
      global:
        audit: false

  govet:
    enable-all: true
    disable:
      - fieldalignment  # Too noisy for this codebase

  staticcheck:
    checks:
      - all
      - -SA1019  # Deprecated (handle separately)

issues:
  exclude-rules:
    # Test files can have unchecked errors
    - path: _test\.go
      linters:
        - errcheck
        - gosec

    # Main files often have deferred close without error check
    - path: main\.go
      linters:
        - errcheck
      text: "Error return value of.*Close.*is not checked"

    # Generated files
    - path: ".*\\.pb\\.go"
      linters:
        - all

  max-issues-per-linter: 50
  max-same-issues: 10

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
