name: Regulatory Compliance Question
 description: Questions about DORA, NIS2, EU AI Act, and other regulatory requirements
 title: "[Regulatory] "
 labels: ["regulatory", "compliance", "dora", "nis2", "eu-ai-act"]
 body:
  - type: dropdown
    id: regulation
    attributes:
      label: Regulation
      description: Which regulation are you asking about?
      options:
        - DORA (Digital Operational Resilience Act)
        - NIS2 (Network and Information Security Directive)
        - EU AI Act
        - Basel III
        - PCI DSS
        - SOX
        - GDPR
        - Other
    validations:
      required: true
  
  - type: dropdown
    id: institution_type
    attributes:
      label: Institution Type
      description: What type of institution are you representing?
      options:
        - Bank
        - Credit Union
        - Investment Firm
        - Insurance Company
        - Fintech Startup
        - Regulatory Consultant
        - Other
    validations:
      required: true
  
  - type: textarea
    id: question
    attributes:
      label: Compliance Question
      description: What's your specific regulatory compliance question?
      placeholder: Describe the requirement you're trying to meet
    validations:
      required: true
  
  - type: textarea
    id: current_challenge
    attributes:
      label: Current Challenge
      description: What specific challenge are you facing with current solutions?
      placeholder: Explain why existing tools don't meet your needs
    validations:
      required: true
  
  - type: textarea
    id: audit_requirements
    attributes:
      label: Audit Requirements
      description: What specific audit trail or explainability requirements do you have?
      placeholder: Glass-box requirements, documentation needs, reporting frequency
    validations:
      required: true
  
  - type: input
    id: deadline
    attributes:
      label: Compliance Deadline
      description: When do you need to be compliant?
      placeholder: e.g., January 2025, Q2 2025, etc.
    validations:
      required: false
  
  - type: checkboxes
    id: urgency
    attributes:
      label: Urgency
      description: How urgent is this compliance requirement?
      options:
        - label: Critical - facing regulatory deadline
          required: false
        - label: High - need solution within 3 months
          required: false
        - label: Medium - planning for next budget cycle
          required: false
        - label: Low - exploratory research
          required: false