extend type Query {
  """
  ✨ Look up a single `Anomaly` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  anomaly(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Anomaly_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Anomaly_FirstRow
  ): Anomaly @fdc_generated(from: "Anomaly", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Dataset` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  dataset(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Dataset_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Dataset_FirstRow
  ): Dataset @fdc_generated(from: "Dataset", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `DetectionTask` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  detectionTask(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: DetectionTask_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: DetectionTask_FirstRow
  ): DetectionTask @fdc_generated(from: "DetectionTask", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `ModelConfiguration` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  modelConfiguration(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ModelConfiguration_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ModelConfiguration_FirstRow
  ): ModelConfiguration @fdc_generated(from: "ModelConfiguration", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ List `Anomaly` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  anomalies(
    """
    Filter condition to narrow down the query results.
    """
    where: Anomaly_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Anomaly_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Anomaly_Having
  ): [Anomaly!]! @fdc_generated(from: "Anomaly", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Dataset` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  datasets(
    """
    Filter condition to narrow down the query results.
    """
    where: Dataset_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Dataset_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Dataset_Having
  ): [Dataset!]! @fdc_generated(from: "Dataset", purpose: QUERY_MULTIPLE)
  """
  ✨ List `DetectionTask` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  detectionTasks(
    """
    Filter condition to narrow down the query results.
    """
    where: DetectionTask_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [DetectionTask_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: DetectionTask_Having
  ): [DetectionTask!]! @fdc_generated(from: "DetectionTask", purpose: QUERY_MULTIPLE)
  """
  ✨ List `ModelConfiguration` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  modelConfigurations(
    """
    Filter condition to narrow down the query results.
    """
    where: ModelConfiguration_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ModelConfiguration_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ModelConfiguration_Having
  ): [ModelConfiguration!]! @fdc_generated(from: "ModelConfiguration", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
}
