extend type Anomaly {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Anomaly", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Anomaly` table.
  """
  _count: Int! @fdc_generated(from: "Anomaly.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Anomaly` table where the `anomalyScore` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  anomalyScore_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Anomaly.anomalyScore", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Anomaly` table where the `dataPointIdentifier` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  dataPointIdentifier_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Anomaly.dataPointIdentifier", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Anomaly` table where the `detectionTaskId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  detectionTaskId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Anomaly.detectionTaskId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Anomaly` table where the `explanation` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  explanation_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Anomaly.explanation", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Anomaly` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Anomaly.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Anomaly` table where the `isAnomaly` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  isAnomaly_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Anomaly.isAnomaly", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Anomaly` table where the `timestamp` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  timestamp_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Anomaly.timestamp", purpose: QUERY_COUNT)
  """
  ✨ Sum the `anomalyScore` field in the `Anomaly` table.
  """
  anomalyScore_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Anomaly.anomalyScore", purpose: QUERY_SUM)
  """
  ✨ Average the `anomalyScore` field in the `Anomaly` table.
  """
  anomalyScore_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Anomaly.anomalyScore", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `anomalyScore` field in the `Anomaly` table.
  """
  anomalyScore_min: Float @fdc_generated(from: "Anomaly.anomalyScore", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `timestamp` field in the `Anomaly` table.
  """
  timestamp_min: Timestamp @fdc_generated(from: "Anomaly.timestamp", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `anomalyScore` field in the `Anomaly` table.
  """
  anomalyScore_max: Float @fdc_generated(from: "Anomaly.anomalyScore", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `timestamp` field in the `Anomaly` table.
  """
  timestamp_max: Timestamp @fdc_generated(from: "Anomaly.timestamp", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Anomaly.id", purpose: GLOBAL_ID)
}
extend type Dataset {
  """
  ✨ List `DetectionTask` objects in a one-to-many relationship (where `DetectionTask`.`dataset` is this object).
  """
  detectionTasks_on_dataset(
    """
    Filter condition to narrow down the query results.
    """
    where: DetectionTask_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [DetectionTask_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: DetectionTask_Having
  ): [DetectionTask!]! @fdc_generated(from: "DetectionTask.dataset", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Dataset", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Dataset` table.
  """
  _count: Int! @fdc_generated(from: "Dataset.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Dataset` table where the `columnInfo` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  columnInfo_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Dataset.columnInfo", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Dataset` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Dataset.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Dataset` table where the `fileLocation` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  fileLocation_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Dataset.fileLocation", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Dataset` table where the `filename` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  filename_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Dataset.filename", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Dataset` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Dataset.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Dataset` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Dataset.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Dataset` table where the `status` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  status_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Dataset.status", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Dataset` table where the `uploadDate` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  uploadDate_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Dataset.uploadDate", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Dataset` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Dataset.userId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `uploadDate` field in the `Dataset` table.
  """
  uploadDate_min: Timestamp @fdc_generated(from: "Dataset.uploadDate", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `uploadDate` field in the `Dataset` table.
  """
  uploadDate_max: Timestamp @fdc_generated(from: "Dataset.uploadDate", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Dataset.id", purpose: GLOBAL_ID)
}
extend type DetectionTask {
  """
  ✨ List `Anomaly` objects in a one-to-many relationship (where `Anomaly`.`detectionTask` is this object).
  """
  anomalies_on_detectionTask(
    """
    Filter condition to narrow down the query results.
    """
    where: Anomaly_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Anomaly_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Anomaly_Having
  ): [Anomaly!]! @fdc_generated(from: "Anomaly.detectionTask", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "DetectionTask", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `DetectionTask` table.
  """
  _count: Int! @fdc_generated(from: "DetectionTask.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `DetectionTask` table where the `datasetId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  datasetId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "DetectionTask.datasetId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `DetectionTask` table where the `endDate` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  endDate_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "DetectionTask.endDate", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `DetectionTask` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "DetectionTask.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `DetectionTask` table where the `modelConfigurationId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  modelConfigurationId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "DetectionTask.modelConfigurationId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `DetectionTask` table where the `notes` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  notes_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "DetectionTask.notes", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `DetectionTask` table where the `resultsLocation` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  resultsLocation_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "DetectionTask.resultsLocation", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `DetectionTask` table where the `startDate` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  startDate_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "DetectionTask.startDate", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `DetectionTask` table where the `status` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  status_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "DetectionTask.status", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `DetectionTask` table where the `taskName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  taskName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "DetectionTask.taskName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `DetectionTask` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "DetectionTask.userId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `endDate` field in the `DetectionTask` table.
  """
  endDate_min: Timestamp @fdc_generated(from: "DetectionTask.endDate", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `startDate` field in the `DetectionTask` table.
  """
  startDate_min: Timestamp @fdc_generated(from: "DetectionTask.startDate", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `endDate` field in the `DetectionTask` table.
  """
  endDate_max: Timestamp @fdc_generated(from: "DetectionTask.endDate", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `startDate` field in the `DetectionTask` table.
  """
  startDate_max: Timestamp @fdc_generated(from: "DetectionTask.startDate", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "DetectionTask.id", purpose: GLOBAL_ID)
}
extend type ModelConfiguration {
  """
  ✨ List `DetectionTask` objects in a one-to-many relationship (where `DetectionTask`.`modelConfiguration` is this object).
  """
  detectionTasks_on_modelConfiguration(
    """
    Filter condition to narrow down the query results.
    """
    where: DetectionTask_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [DetectionTask_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: DetectionTask_Having
  ): [DetectionTask!]! @fdc_generated(from: "DetectionTask.modelConfiguration", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "ModelConfiguration", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `ModelConfiguration` table.
  """
  _count: Int! @fdc_generated(from: "ModelConfiguration.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ModelConfiguration` table where the `algorithmType` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  algorithmType_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ModelConfiguration.algorithmType", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ModelConfiguration` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ModelConfiguration.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ModelConfiguration` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ModelConfiguration.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ModelConfiguration` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ModelConfiguration.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ModelConfiguration` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ModelConfiguration.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ModelConfiguration` table where the `parameters` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  parameters_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ModelConfiguration.parameters", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ModelConfiguration` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ModelConfiguration.userId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `ModelConfiguration` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "ModelConfiguration.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `ModelConfiguration` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "ModelConfiguration.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "ModelConfiguration.id", purpose: GLOBAL_ID)
}
extend type User {
  """
  ✨ List `Dataset` objects in a one-to-many relationship (where `Dataset`.`user` is this object).
  """
  datasets_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: Dataset_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Dataset_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Dataset_Having
  ): [Dataset!]! @fdc_generated(from: "Dataset.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `DetectionTask` objects in a one-to-many relationship (where `DetectionTask`.`user` is this object).
  """
  detectionTasks_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: DetectionTask_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [DetectionTask_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: DetectionTask_Having
  ): [DetectionTask!]! @fdc_generated(from: "DetectionTask.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `ModelConfiguration` objects in a one-to-many relationship (where `ModelConfiguration`.`user` is this object).
  """
  modelConfigurations_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: ModelConfiguration_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ModelConfiguration_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ModelConfiguration_Having
  ): [ModelConfiguration!]! @fdc_generated(from: "ModelConfiguration.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "User", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `User` table.
  """
  _count: Int! @fdc_generated(from: "User.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `displayName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  displayName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.displayName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `email` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  email_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.email", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `photoUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  photoUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.photoUrl", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `User` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "User.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `User` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "User.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "User.id", purpose: GLOBAL_ID)
}
