type User @table {
  displayName: String!
  createdAt: Timestamp!
  email: String
  photoUrl: String
}

type Dataset @table {
  user: User!
  name: String!
  filename: String!
  uploadDate: Timestamp!
  fileLocation: String!
  status: String!
  description: String
  columnInfo: String
}

type ModelConfiguration @table {
  user: User!
  name: String!
  algorithmType: String!
  createdAt: Timestamp!
  parameters: String
  description: String
}

type DetectionTask @table {
  user: User!
  dataset: Dataset!
  modelConfiguration: ModelConfiguration!
  taskName: String!
  startDate: Timestamp!
  status: String!
  endDate: Timestamp
  resultsLocation: String
  notes: String
}

type Anomaly @table {
  detectionTask: DetectionTask!
  dataPointIdentifier: String!
  anomalyScore: Float!
  isAnomaly: Boolean!
  explanation: String
  timestamp: Timestamp
}